name: Rainbow the tables!

on:
  push:
    branches:
    - main
jobs;
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version:'3.12'
      
      - name: Update pip
        run: | 
          python -m pip install --pre -U pip
          python -m ensurepip
      
      - name: Install Dependencies
        run: |
          python -m pip install -U numpy
          python -m pip install -U orjson
      
      - name: Run Hashing of everything
        run |
          python hasher.py
          
          